services:
  vault-unlock:
    image: restic/restic:latest
    container_name: restic_unlocker
    volumes:
      - D:/ResticVault/data:/data
    environment:
      - RESTIC_REPOSITORY=/data/robert
      - RESTIC_PASSWORD=robertjames
    command: unlock

  vault-repair-index:
    image: restic/restic:latest
    container_name: restic_repair_index
    volumes:
      - D:/ResticVault/data:/data
    environment:
      - RESTIC_REPOSITORY=/data/robert
      - RESTIC_PASSWORD=robertjames
    command: repair index

  vault-repair-snapshots:
    image: restic/restic:latest
    container_name: restic_repair_snapshots
    volumes:
      - D:/ResticVault/data:/data
    environment:
      - RESTIC_REPOSITORY=/data/robert
      - RESTIC_PASSWORD=robertjames
    command: repair snapshots

  vault-repair-packs:
    image: restic/restic:latest
    container_name: restic_repair_packs
    volumes:
      - D:/ResticVault/data:/data
    environment:
      - RESTIC_REPOSITORY=/data/robert
      - RESTIC_PASSWORD=robertjames
    command: repair packs

  vault-check:
    image: restic/restic:latest
    container_name: restic_check
    volumes:
      - D:/ResticVault/data:/data
    environment:
      - RESTIC_REPOSITORY=/data/robert
      - RESTIC_PASSWORD=robertjames
    command: check

  vault-maintenance:
    image: restic/restic:latest
    container_name: restic_janitor
    volumes:
      - D:/ResticVault/data:/data
    environment:
      - RESTIC_REPOSITORY=/data/robert
      - RESTIC_PASSWORD=robertjames
    command: forget --keep-daily 30 --keep-weekly 12 --keep-monthly 12 --prune

  rest-server:
    image: restic/rest-server:latest
    container_name: restic_vault
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - D:/ResticVault/data:/data
    environment:
      - OPTIONS=--append-only --private-repos
      - RESTIC_USER=robert
      - RESTIC_PASSWORD=robertjames