services:
  vault-unlock:
    image: restic/restic:latest
    container_name: restic_unlocker
    volumes:
      - D:/ResticVault/data:/data
    environment:
      - RESTIC_REPOSITORY=/data/robert
      - RESTIC_PASSWORD=robertjames
    command: unlock

  vault-maintenance:
    image: restic/restic:latest
    container_name: restic_janitor
    depends_on:
      vault-unlock:
        condition: service_completed_successfully
    volumes:
      - D:/ResticVault/data:/data
    environment:
      - RESTIC_REPOSITORY=/data/robert
      - RESTIC_PASSWORD=robertjames
    command: forget --keep-daily 30 --keep-weekly 12 --keep-monthly 12 --prune

  rest-server:
    image: restic/rest-server:latest
    container_name: restic_vault
    restart: always
    depends_on:
      vault-maintenance:
        condition: service_completed_successfully
    ports:
      - "8000:8000"
    volumes:
      - D:/ResticVault/data:/data
    environment:
      - OPTIONS=--append-only --private-repos
      - RESTIC_USER=robert
      - RESTIC_PASSWORD=robertjames